name: first workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v7

            - name: welcome message
              run: echo "My first github action job"

            - name: List files
              run : ls

            - name: Read file
              run: cat README.md
            
            - name: Generate ASCII artwork
              run: |
                echo "run cowsay command"
#                cowsay -f dragon "I am a dragon" >> dragon.txt